[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[server]
maxUploadSize = 20
maxMessageSize = 100

[deprecation]
showPyplotGlobalUse = false 